name: IEnergy
description: 
  
url: "http://ienergy-test.github.io"

paginate: 10

markdown: rdiscount

# translation tags
t:
  ita:
    home:  "Home"
    about: "About"
    developer : "Sviluppatori"
    contact : "Contatti"
    language : "Lingua"
    back_to_top : "Torna su"
  eng:
    home:  "Home"
    about: "About"
    developer : "Developer"
    contact : "Contact"
    language : "Language"
    back_to_top : "Back to top"