name: IEnergy
description: 
  
url: "http://iEnergy.github.io"

paginate: 10

markdown: rdiscount

# translation tags
t:
  ita:
    home:  "Home"
    about: "About"
    developer : "Sviluppatori"
    documentation : "Documentazione"
    contact : "Contatti"
    language : "Lingua"
    back_to_top : "Torna su"
    architecture : "Architettura"
    components : "Componenti"
    installation : "Installazione"
    restapi : "REST API"
  eng:
    home:  "Home"
    about: "About"
    developer : "Developer"
    documentation : "Documentation"
    contact : "Contact"
    language : "Language"
    back_to_top : "Back to top"
    architecture : "Architecture"
    components : "Components"
    installation : "Installation"
    restapi : "REST API"